package com.dolo.patient.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.dolo.patient.auth.AuthStep
import com.dolo.patient.auth.AuthViewModel
import com.dolo.patient.data.*
import com.dolo.patient.data.model.Doctor
import com.dolo.patient.data.model.Session
import com.dolo.patient.ui.components.*
import com.dolo.patient.ui.theme.*

private val page=Modifier.fillMaxSize().background(DoloBackground)

@Composable fun SplashScreen(onContinue:()->Unit){Box(page.padding(28.dp),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){BrandLogo();Spacer(Modifier.height(28.dp));Icon(Icons.Outlined.HealthAndSafety,null,tint=DoloTeal,modifier=Modifier.size(130.dp));Text("Book. Track. Visit.",style=MaterialTheme.typography.headlineMedium);Text("Worry less.",color=DoloTeal,fontSize=22.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(34.dp));PrimaryButton("Get started",onContinue)}}}
@Composable fun LoginScreen(auth:AuthViewModel,onLogin:()->Unit){val s=auth.uiState;LaunchedEffect(s.step){if(s.step==AuthStep.AUTHENTICATED)onLogin()};Column(page.padding(24.dp),verticalArrangement=Arrangement.Center){BrandLogo();Spacer(Modifier.height(30.dp));Text(if(s.step==AuthStep.OTP)"Verify OTP" else "Welcome Back!",style=MaterialTheme.typography.headlineMedium);Text(if(s.step==AuthStep.OTP)"Code sent to +91 "+s.phone else "Login using your mobile number",color=DoloMuted);Spacer(Modifier.height(20.dp));if(s.step==AuthStep.PHONE){OutlinedTextField(s.phone,auth::updatePhone,Modifier.fillMaxWidth(),label={Text("Mobile number")},prefix={Text("+91 ")},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Phone),singleLine=true);Spacer(Modifier.height(16.dp));PrimaryButton("Send OTP",auth::requestOtp,s.phone.length==10)}else{OutlinedTextField(s.otp,auth::updateOtp,Modifier.fillMaxWidth(),label={Text("6-digit OTP")},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.NumberPassword),singleLine=true);Text("Demo OTP: 123456",color=DoloTeal,modifier=Modifier.padding(vertical=12.dp));PrimaryButton("Verify & Continue",auth::verifyOtp,s.otp.length==6);TextButton(auth::editPhone){Text("Change mobile number")}};s.error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}}

@Composable fun HomeScreen(onCategories:()->Unit,onDoctor:(String)->Unit,onHistory:()->Unit,onFavourites:()->Unit,onLogout:()->Unit,state:PatientUiState,onSearch:(String)->Unit){var q by remember{mutableStateOf("")};Scaffold(containerColor=DoloBackground,bottomBar={DoloBottomBar()}){p->LazyColumn(Modifier.padding(p).padding(20.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){item{Row(verticalAlignment=Alignment.CenterVertically){BrandLogo();Spacer(Modifier.weight(1f));IconButton(onHistory){Icon(Icons.Outlined.History,"History")};IconButton(onLogout){Icon(Icons.Outlined.Logout,"Logout")}}};item{Text("Welcome, Rahul Sharma 👋",fontSize=26.sp,fontWeight=FontWeight.ExtraBold,color=DoloTeal)};item{OutlinedTextField(q,{q=it},Modifier.fillMaxWidth(),placeholder={Text("Search doctor, specialty or clinic")},leadingIcon={Icon(Icons.Outlined.Search,null)},trailingIcon={IconButton({onSearch(q)}){Icon(Icons.Outlined.ArrowForward,null)}},singleLine=true,shape=RoundedCornerShape(18.dp))};item{Row(horizontalArrangement=Arrangement.spacedBy(12.dp)){MetricCard("Your token",(state.active?.token?:0).toString(),Modifier.weight(1f));MetricCard("In process","12",Modifier.weight(1f),Color(0xFF1769D2))}};item{PrimaryButton("Browse doctor categories",onCategories)};item{Row(verticalAlignment=Alignment.CenterVertically){Text("Favourite Doctors",style=MaterialTheme.typography.titleLarge);Spacer(Modifier.weight(1f));TextButton(onFavourites){Text("View all")}}};val favs=DummyData.doctors.filter{it.id in state.favouriteIds};if(favs.isEmpty())item{EmptyCard("Tap the heart on a doctor to save them.")}else items(favs){DoctorCard(it,true,{onDoctor(it.id)},{})}}}}

@Composable fun CategoriesScreen(onBack:()->Unit,onSelect:(String)->Unit){Column(page.padding(20.dp)){ScreenTitle("Categories",onBack);Spacer(Modifier.height(18.dp));Text("Find the right specialist",style=MaterialTheme.typography.headlineMedium);Spacer(Modifier.height(16.dp));LazyVerticalGrid(GridCells.Fixed(2),horizontalArrangement=Arrangement.spacedBy(12.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){items(DummyData.categories){c->Card(Modifier.height(145.dp).clickable{onSelect(c.name)},shape=RoundedCornerShape(22.dp)){Column(Modifier.fillMaxSize().padding(16.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.SpaceEvenly){Text(c.symbol,fontSize=40.sp,color=DoloTeal);Text(c.name,textAlign=TextAlign.Center,fontWeight=FontWeight.Bold)}}}}}}

@Composable fun DoctorListScreen(category:String,onBack:()->Unit,state:PatientUiState,onSearch:(String)->Unit,onDoctor:(String)->Unit,onFavourite:(String)->Unit){var q by remember(category){mutableStateOf(if(category=="All")state.query else "")};LaunchedEffect(category){onSearch(q)};Scaffold(containerColor=DoloBackground,bottomBar={DoloBottomBar()}){p->LazyColumn(Modifier.padding(p).padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{ScreenTitle(if(category=="All")"Search Doctors" else category,onBack)};item{OutlinedTextField(q,{q=it;onSearch(it)},Modifier.fillMaxWidth(),placeholder={Text("Search doctors or clinics")},leadingIcon={Icon(Icons.Outlined.Search,null)},singleLine=true,shape=RoundedCornerShape(18.dp))};if(state.doctors.isEmpty())item{EmptyCard("No doctors match your search.")}else items(state.doctors){d->DoctorCard(d,d.id in state.favouriteIds,{onDoctor(d.id)},{onFavourite(d.id)})}}}}

@Composable fun DoctorCard(d:Doctor,favourite:Boolean,onOpen:()->Unit,onFavourite:()->Unit){Card(Modifier.fillMaxWidth().clickable(onClick=onOpen),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(16.dp)){Row(verticalAlignment=Alignment.CenterVertically){Surface(shape=CircleShape,color=DoloSurfaceAlt,modifier=Modifier.size(64.dp)){Icon(Icons.Outlined.MedicalServices,null,tint=DoloTeal,modifier=Modifier.padding(15.dp))};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(d.name,fontWeight=FontWeight.Bold,fontSize=18.sp);Text(d.specialty,color=DoloMuted);Text("★ "+d.rating+"  •  "+d.experienceYears+"+ years",fontSize=12.sp);Text(d.clinic,color=DoloMuted,fontSize=12.sp)};IconButton(onFavourite){Icon(if(favourite)Icons.Outlined.Favorite else Icons.Outlined.FavoriteBorder,"Favourite",tint=if(favourite)Color.Red else DoloTeal)}};Spacer(Modifier.height(10.dp));Row(verticalAlignment=Alignment.CenterVertically){Text("₹"+d.consultationFee,fontWeight=FontWeight.Bold);Spacer(Modifier.weight(1f));Button(onClick=onOpen){Text("View & Book")}}}}}

@Composable fun DoctorDetailsScreen(id:String,favourite:Boolean,onBack:()->Unit,onFavourite:()->Unit,onBook:()->Unit){val d=DummyData.doctors.firstOrNull{it.id==id}?:DummyData.doctors.first();LazyColumn(page.padding(20.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){item{ScreenTitle("Doctor Details",onBack)};item{DoctorCard(d,favourite,{},onFavourite)};item{InfoCard("About","Experienced "+d.specialty.lowercase()+" focused on clear guidance and patient-friendly care.")};item{InfoCard("Clinic",d.clinic+"\nWalk-in sessions: Morning and Evening")};item{InfoCard("Patient reviews","★ "+d.rating+" / 5\nVerified patient feedback will appear here.")};item{PrimaryButton("Book Walk-in Appointment",onBook)}}}
@Composable fun FavouritesScreen(state:PatientUiState,onBack:()->Unit,onDoctor:(String)->Unit,onFavourite:(String)->Unit){val ds=DummyData.doctors.filter{it.id in state.favouriteIds};LazyColumn(page.padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{ScreenTitle("Favourite Doctors",onBack)};if(ds.isEmpty())item{EmptyCard("You have not saved any doctors yet.")}else items(ds){DoctorCard(it,true,{onDoctor(it.id)},{onFavourite(it.id)})}}}
@Composable fun AppointmentHistoryScreen(list:List<Appointment>,onBack:()->Unit){LazyColumn(page.padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{ScreenTitle("Appointment History",onBack)};if(list.isEmpty())item{EmptyCard("Your booked appointments will appear here.")}else items(list){a->Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp)){Column(Modifier.padding(16.dp)){Row{Text(a.doctorName,fontWeight=FontWeight.Bold,modifier=Modifier.weight(1f));AssistChip({},label={Text(a.status)})};Text(a.clinic,color=DoloMuted);Text(a.date+" • "+a.session.name.lowercase().replaceFirstChar(Char::uppercase)+" session");Text("Token "+a.token,color=DoloTeal,fontSize=22.sp,fontWeight=FontWeight.Bold)}}}}}

@Composable fun BookingScreen(doctorId:String,onBack:()->Unit,onConfirm:(String,Session)->Unit){val d=DummyData.doctors.firstOrNull{it.id==doctorId}?:DummyData.doctors.first();var session by remember{mutableStateOf(Session.MORNING)};LazyColumn(page.padding(20.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){item{ScreenTitle("Book Appointment",onBack)};item{InfoCard(d.name,d.specialty+"\n"+d.clinic)};item{Text("Choose walk-in session",style=MaterialTheme.typography.titleLarge)};item{SessionChoice("Morning","09:00 AM – 01:00 PM",session==Session.MORNING){session=Session.MORNING}};item{SessionChoice("Evening","05:00 PM – 09:00 PM",session==Session.EVENING){session=Session.EVENING}};item{InfoCard("Payment summary","Consultation ₹"+d.consultationFee+"\nService charge ₹20\nTotal ₹"+(d.consultationFee+20))};item{PrimaryButton("Confirm Booking",onClick={onConfirm(d.id,session)})}}}
@Composable fun ConfirmationScreen(doctorId:String,session:String,appointment:Appointment?=null,onDone:()->Unit){val d=DummyData.doctors.firstOrNull{it.id==doctorId}?:DummyData.doctors.first();Column(page.padding(24.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Icon(Icons.Outlined.CheckCircle,null,tint=DoloTeal,modifier=Modifier.size(80.dp));Text("Booking Confirmed!",style=MaterialTheme.typography.headlineMedium);Text("YOUR TOKEN NUMBER",modifier=Modifier.padding(top=24.dp));Text((appointment?.token?:0).toString(),fontSize=88.sp,fontWeight=FontWeight.ExtraBold,color=DoloTeal);InfoCard(appointment?.doctorName?:d.name,(appointment?.clinic?:d.clinic)+"\n"+(appointment?.date?:"Today")+" • "+session.lowercase().replaceFirstChar(Char::uppercase)+" session");Spacer(Modifier.height(20.dp));PrimaryButton("Back to Home",onDone)}}

@Composable private fun SessionChoice(title:String,time:String,selected:Boolean,onClick:()->Unit){Card(Modifier.fillMaxWidth().clickable(onClick=onClick),colors=CardDefaults.cardColors(containerColor=if(selected)DoloSurfaceAlt else Color.White),shape=RoundedCornerShape(18.dp)){Row(Modifier.padding(18.dp),verticalAlignment=Alignment.CenterVertically){Icon(if(title=="Morning")Icons.Outlined.LightMode else Icons.Outlined.DarkMode,null,tint=DoloTeal);Spacer(Modifier.width(14.dp));Column(Modifier.weight(1f)){Text(title+" Session",fontWeight=FontWeight.Bold);Text(time,color=DoloMuted)};if(selected)Icon(Icons.Outlined.CheckCircle,null,tint=DoloTeal)}}}
@Composable private fun InfoCard(title:String,text:String){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp)){Column(Modifier.padding(18.dp)){Text(title,fontWeight=FontWeight.Bold,fontSize=18.sp);Spacer(Modifier.height(6.dp));Text(text,color=DoloMuted)}}}
@Composable private fun EmptyCard(text:String){Card(Modifier.fillMaxWidth(),colors=CardDefaults.cardColors(containerColor=DoloSurfaceAlt),shape=RoundedCornerShape(20.dp)){Text(text,Modifier.padding(22.dp),textAlign=TextAlign.Center,color=DoloMuted)}}
